### ISSUE TITLE
Default tasks in aliases.yaml are not overwritten

### ISSUE THREAD

**Issue by ghost** [Yoast/plugin-grunt-tasks#14]
### Please give us a description of what happened.
`aliases.yaml` in the `yoast-seo-granular-control` repo contains the following code:
```
build:
  - 'build:css'
  - 'build:js'
```

However, when running `grunt build` in that repo, the `build` alias from `plugin-grunt-tasks/config/aliases.yaml` is still carried out. This means that it is not possible to overwrite those default tasks (such as `build`) in other repos.

### Please describe what you expected to happen and why.
When running `grunt build` in the `yoast-seo-granular-control` repo, I expected only `build:css` and `build:js` to be executed, and not also `build:images` and `build:i18n` (these latter two tasks are defined in the `plugin-grunt-tasks` repo.

### How can we reproduce this behavior?
1. In the terminal, navigate to the `yoast-seo-granular-control` repo and run `grunt artifact`.
2. See that the `imagemin`, `addtextdomain` and `makepot` tasks are run, even though these are not specified in `aliases.yaml`.
3. See that `build:images` and `build:i18n` ARE present in `plugin-grunt-tasks/config/aliases.yaml`.
4. In `yoast-seo-granular-control/config/aliases.yaml` if you change the `build` tasks, you will see these changes reflected in the terminal (for example, switch around the order of `build:css` and `build:js`). This doesn't change the fact that `build:images` and `build:i18n` are ALSO executed.

### Technical info
* WordPress version:
* Yoast SEO version:

* If relevant, which editor is affected (or editors): 
- [ ] Classic Editor
- [ ] Gutenberg
- [ ] Classic Editor plugin

* Which browser is affected (or browsers): 
- [ ] IE11
- [ ] Edge
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

* Relevant plugins in case of a bug:

* Tested with theme:

**Comment by IreneStr** [comment]
Solution: 
- Rename `build` in this plugin to `build-default`.
- Release `plugin-grunt-tasks`
- Check all plugins that use plugin-grunt-tasks and use the above `build-default` where necessary. 
- Remove this line: https://github.com/Yoast/yoast-seo-granular-control/pull/5/files#diff-35b4a816e0441e6a375cd925af50752cR35

**Comment by jdevalk** [comment]
Fixed by cb6fc3a1a3b747000331161a5ff5f52df659aa29
